# Generated by Django 5.0.6 on 2024-07-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_mm', models.TextField()),
                ('answer_mm', models.TextField()),
                ('question_en', models.TextField()),
                ('answer_en', models.TextField()),
            ],
        ),
    ]
