# Generated by Django 5.0.6 on 2024-07-26 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_questions_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Parent_Question',
        ),
    ]
