# Generated by Django 5.0.6 on 2024-07-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_question_parent_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_mm', models.TextField()),
                ('answer_mm', models.TextField()),
                ('question_en', models.TextField()),
                ('answer_en', models.TextField()),
            ],
            options={
                'verbose_name': 'Tutor Question',
                'verbose_name_plural': 'Tutor Questions',
            },
        ),
        migrations.AlterModelOptions(
            name='parent_question',
            options={'verbose_name': 'Parent Question', 'verbose_name_plural': 'Parent Questions'},
        ),
    ]
