# Generated by Django 5.0.6 on 2024-07-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_homeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
