# Generated by Django 5.0.6 on 2024-08-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='subtitle',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
