# Generated by Django 5.0.6 on 2024-09-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
