# Generated by Django 5.0.6 on 2024-09-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
