# Generated by Django 5.0.6 on 2024-09-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_rename_date_event_eventdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='isHide',
            field=models.BooleanField(default=False),
        ),
    ]
