# Generated by Django 5.0.6 on 2024-09-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_event_ishide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='isHide',
        ),
        migrations.AddField(
            model_name='event',
            name='toPresent',
            field=models.BooleanField(default=True),
        ),
    ]
