# Generated by Django 5.0.6 on 2024-09-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isVideo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='videoUrl',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
