# Generated by Django 5.0.6 on 2024-10-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_enquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='isVideo',
            new_name='arranged',
        ),
    ]
