# Generated by Django 5.0.6 on 2025-06-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadableApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('appstore_link', models.URLField(blank=True, null=True)),
                ('playstore_link', models.URLField(blank=True, null=True)),
                ('direct_download', models.FileField(blank=True, null=True, upload_to='downloads/')),
            ],
        ),
    ]
