# Generated by Django 5.0.6 on 2025-06-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_downloadableapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='downloadableapp',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='downloadableapp',
            name='title_mm',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
