# Generated by Django 5.0.6 on 2025-06-21 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_rename_title_downloadableapp_title_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadableapp',
            options={'verbose_name': 'App', 'verbose_name_plural': 'Apps'},
        ),
    ]
